Name: Janak Mandavgade

Sec : A

Roll no : 43  

Batch : A2

Subject : ML Lab

Aim : Implementation of KNN algorithm for classification using Iris dataset.

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data  # Features
y = iris.target  # Target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a KNN classifier with a specified number of neighbors (e.g., k=3)
k = 3
knn_classifier = KNeighborsClassifier(n_neighbors=k)

# Fit the model to the training data
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn_classifier.predict(X_test)

# Evaluate the model
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Confusion Matrix:")
print(confusion_mat)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
# Assume you have new_data as a NumPy array with the same number of features as the Iris dataset
new_data = np.array([[5.1, 3.5, 1.4, 0.2]])  # Replace with your own data

# Use the trained KNN classifier to predict the class for new_data
predicted_class = knn_classifier.predict(new_data)

# Map the predicted class index to the actual class label
predicted_class_label = iris.target_names[predicted_class[0]]

print(f"The predicted class for new_data is: {predicted_class_label}")

The predicted class for new_data is: setosa
